/* DO NOT EDIT THIS FILE - it is machine generated */

#include "complex_Complex.h"
/* Header for class Complex__custom */

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Complex
 * Method:    playWithFields
 * Signature: (Lcomplex/Sub;)V
 * Imported methods:
 *   void Complex_playWithStatics( Complex )
 *   void Sub_foo( Sub )
 *   void Complex_playWithFields( Complex, Sub )
 *   void Complex_StaticFoo(  )
 *   void assign_Sub_i( Sub self, Sub in_value )
 *   Sub get_Sub_i( Sub self )
 *   void assign_Complex_local_sub( Complex self, Complex in_value )
 *   Complex get_Complex_local_sub( Complex self )
 *   jint super_Complex_hashCode( Complex );
 *   void new_Complex__0003cinit_0003e(  )
 */
void Complex_playWithFields__impl
 ( Complex self, Sub sub ) {
	assign_Complex_local_sub( self, sub );

	Sub local_sub = get_Complex_local_sub( self );
	jint i = get_Sub_i( local_sub );
	printf( "playWithFields: local_sub.i == {%d}\n", i );

	assign_Sub_i( local_sub, 12345 );
}

/*
 * Class:     Complex
 * Method:    playWithMethods
 * Signature: ()V
 * Imported methods:
 *   void Complex_playWithStatics( Complex )
 *   void Sub_foo( Sub )
 *   void Complex_playWithFields( Complex, Sub )
 *   void Complex_StaticFoo(  )
 *   void assign_Sub_i( Sub self, Sub in_value )
 *   Sub get_Sub_i( Sub self )
 *   void assign_Complex_local_sub( Complex self, Complex in_value )
 *   Complex get_Complex_local_sub( Complex self )
 *   jint super_Complex_hashCode( Complex );
 *   void new_Complex__0003cinit_0003e(  )
 */
void Complex_playWithMethods__impl
 ( Complex self ) {
	Complex_playWithStatics( self );

	Sub s = Complex_playWithConstructors( self );
	Complex_playWithFields( self, s );
	Sub_foo( s );
}


/*
 * Class:     Complex
 * Method:    playWithStatics
 * Signature: ()V
 * Imported methods:
 *   void Complex_playWithStatics( Complex )
 *   void Sub_foo( Sub )
 *   void Complex_playWithFields( Complex, Sub )
 *   void Complex_StaticFoo(  )
 *   void assign_Sub_i( Sub self, Sub in_value )
 *   Sub get_Sub_i( Sub self )
 *   void assign_Complex_local_sub( Complex self, Complex in_value )
 *   Complex get_Complex_local_sub( Complex self )
 *   jint super_Complex_hashCode( Complex );
 *   void new_Complex__0003cinit_0003e(  )
 */
void Complex_playWithStatics__impl
 ( Complex self ) {
	Complex_StaticFoo();
	Complex_StaticBar();
}

/*
 * Class:     complex_Complex
 * Method:    StaticBar
 * Signature: ()V
 * Imported methods:
 *   void Sub_foo( Sub self )
 *   Sub Complex_playWithConstructors( Complex self )
 *   void Complex_playWithFields( Complex self, Sub arg0 )
 *   void Complex_StaticBar(  )
 *   void Complex_StaticFoo(  )
 *   void Complex_playWithStatics( Complex self )
 *   void assign_Complex_local_sub( Complex self, Sub in_value )
 *   Sub get_Complex_local_sub( Complex self )
 *   void assign_Sub_i( Sub self, jint in_value )
 *   jint get_Sub_i( Sub self )
 *   jint super_Complex_hashCode( Complex self )
 *   Sub new_Sub(  )
 */
void Complex_StaticBar__impl() {
	printf( "StaticBar\n" );
}

/*
 * Class:     Complex
 * Method:    playWithConstructors
 * Signature: ()Lcomplex/Sub;
 * Imported methods:
 *   void Complex_playWithStatics( Complex )
 *   void Sub_foo( Sub )
 *   void Complex_playWithFields( Complex, Sub )
 *   void Complex_StaticFoo(  )
 *   void assign_Sub_i( Sub self, Sub in_value )
 *   Sub get_Sub_i( Sub self )
 *   void assign_Complex_local_sub( Complex self, Complex in_value )
 *   Complex get_Complex_local_sub( Complex self )
 *   jint super_Complex_hashCode( Complex );
 *   void new_Complex__0003cinit_0003e(  )
 */
Sub Complex_playWithConstructors__impl
 ( Complex self ) {
	return new_Sub();
}

/*
 * Class:     Complex
 * Method:    hashCode
 * Signature: ()I
 * Imported methods:
 *   void Complex_playWithStatics( Complex )
 *   void Sub_foo( Sub )
 *   void Complex_playWithFields( Complex, Sub )
 *   void Complex_StaticFoo(  )
 *   void assign_Sub_i( Sub self, Sub in_value )
 *   Sub get_Sub_i( Sub self )
 *   void assign_Complex_local_sub( Complex self, Complex in_value )
 *   Complex get_Complex_local_sub( Complex self )
 *   jint super_Complex_hashCode( Complex );
 *   void new_Complex__0003cinit_0003e(  )
 */
jint Complex_hashCode__impl
 ( Complex self ) {
	jint s = super_Complex_hashCode( self );
	return 2 * s;
}

#ifdef __cplusplus
}
#endif
